//
//  ServerConstant.swift
//  DDD
//
//  Created by Wdev3 on 30/10/20.
//  Copyright © 2020 Wdev3. All rights reserved.
//

import Foundation

//Auth
let kUserData = "User"
let kUserId = "UserId"
let kAccessToken = "authentication"
let kDisplayImage = "DisplayImage"
let kDisplayImageURL = "DisplayImageURL"
let kUserType = "UserType"
let kMobile = "Mobile"
let kFirstName = "firstName"
let kLastName = "lastName"
let kEmail = "email"
let klocation = "location"
let kisManualEmail = "isManualEmail"

let klatitude = "latitude"
let klongitude = "longitude"
let kpassword = "password"
let kdeviceType = "deviceType"
let kdeviceToken = "deviceToken"
let kForgotToken = "ForgotToken"
let KoldPassword = "oldPassword"
let KnewPassword = "newPassword"

let klangType = "langType"
let kdeviceId = "deviceId"
let kip_address = "ip_address"
let krole = "role"
let kauthProvider = "authProvider"
let klocationDetails = "locationDetails"
let kbrowser = "browser"
let kbrowserVersion = "browserVersion"
let kplatform = "platform"
let kfull_user_agent_string = "full_user_agent_string"
let ktoken = "token"
let kfiles = "files"
let kmediaName = "mediaName"
let kmediaBaseUrl = "mediaBaseUrl"
let kvideoThumbImgUrl = "videoThumbImgUrl"
let ksearch = "search"
let klimit = "limit"
let kpage = "page"
let kisNear = "isNear"
let kupcomingAppointments = "upcomingAppointments"

let kprofileStatus = "profileStatus"
let kfillpassword = "fillpassword"
let kemergencyContact = "emergencyContact"
let kcontactPersonName = "contactPersonName"
let kpreferredLanguage = "preferredLanguage"
let kid = "id"
let klname = "lname"
let kcountry = "country"
let kstate = "state"
let kstateName = "stateName"
let kzipcode = "zipcode"
let kreferralCode = "referralCode"
let ktimeZone = "timeZone"
let kdob = "dob"
let kfname = "FirstName"
let kaddress = "address"
let kverificationCode = "verificationCode"
let kappNotification = "appNotification"
let kimage = "image"
let kunitNo = "unitNo"
let kname = "name"
let kforgotCode = "forgotCode"
let kcity = "city"
let kcityName = "cityName"
let konsitePrice = "onsitePrice"
let kactiveStatus = "activeStatus"
let kprofileimage = "profileImageUrl"
let kmobilePrice = "mobilePrice"
let kthumbprofileimage = "profileImageThumbUrl"
let kvirtualPrice = "virtualPrice"
let kscheduled = "scheduled"
let kgender = "gender"
let kage = "age"
let kbirthdate = "birthdate"
let kmname = "mname"
let kuserName = "userName"
let kphone = "phone"
let kisVoiceEnrollment = "isVoiceEnrollment"
let knewContactNotification = "newContactNotification"
let kvoiceitid = "voiceitid"

//Language
let klanguageId = "languageId"
let klanguageName = "languageName"
let kisSelectLanguage = "isSelectLanguage"

//Chat
let kfriendUserId = "friendUserId"
let kgroupType = "groupType"
let kisAdmin = "isAdmin"
let kmessageId = "messageId"
let ksender = "sender"
let kunreadMessages = "unreadMessages"
let kmessage = "message"
let kthumbImage = "thumbImage"
let krecipient_id = "recipient_id"

//Ticket
let kpriority = "priority"
let kclosedDate = "closedDate"
let kreopenDate = "reopenDate"
let khookMethod = "hookMethod"
let kticket_id = "ticket_id"
let kreplyType = "replyType"
let kticketId = "ticketId"
let ktime = "time"
let klastMsgTime = "lastMsgTime"
let kforReply = "forReply"
let ksenderImage = "senderImage"
let ksenderName = "senderName"
let kcreatedDate = "createdDate"
let kfaqId = "faqId"
let klastReplay = "lastReplay"

//Login History
let kauth_provider = "auth_provider"
let kauth_id = "auth_id"
let kquestions = "questions"

let kfeedback = "feedback"
let krating = "rating"
let khowLikely = "howLikely"
let kexpectations = "expectations"

let krelation = "relation"
let kanswer = "answer"
let kquestion_answer = "question_answer"
let kdob_relation = "dob_relation"
let kmethod = "method"

let kpageId = "pageId"
let kkey = "key"
let kdescription = "description"
let kuserId = "userId"
let ktitle = "title"
let ksharingLink = "sharingLink"
let kisBookmark = "isBookmark"

//City
let kcode = "code"
let kcountryId = "countryId"
let kstateId = "stateId"
let kcityId = "cityId"
let ktype = "type"

let kcolor = "color"
let kimageUrl = "imageUrl"
let kthumbImageUrl = "thumbImageUrl"
let ktotalHealthProfessionals = "totalHealthProfessionals"

let kuserSearchHistoryId = "userSearchHistoryId"
let kkeyword = "keyword"

let kresourcesAndBlogs = "resourcesAndBlogs"
let kresourceId = "resourceId"
let kcategoryId = "categoryId"
let kcategoryName = "categoryName"
let kemail = "email"
let kbio = "bio"
let kisFounder = "isFounder"
let kratingAverage = "ratingAverage"
let knextAvailable = "nextAvailable"
let kexperienceYears = "experienceYears"
let kprofessionNames = "professionNames"
let kisFavorite = "isFavorite"
let kinvitedBy = "invitedBy"

let kdoctorId = "doctorId"

let kuserAvailabilityId = "userAvailabilityId"
let kappointmentType = "appointmentType"
let kdateTime = "dateTime"
let ktiming = "timing"
let kisBooked = "isBooked"
let kdayAndDate = "dayAndDate"
let ktotalSlotsAvailable = "totalSlotsAvailable"
let kdateTimeFormat = "dateTimeFormat"
let kdateFormat = "dateFormat"
let ktimeFormat = "timeFormat"
let kslotsAvailable = "slotsAvailable"
let kavailability = "availability"
let kisvitualmeeting = "isvitualmeeting"

let kdoctorData = "doctorData"
let kavailabilityData = "availabilityData"

//card
let kholderName = "holderName"
let knumber = "number"
let kexpMonth = "expMonth"
let kexpYear = "expYear"
let kmonth = "month"
let kyear = "year"
let kisDefault = "isDefault"
let kcvv = "cvv"
let kis_selected = "is_selected"
let kfullurl = "fullurl"
let kis_expire = "is_expire"
let kcardId = "cardId"
let kgroupStatus = "groupStatus"
let kgroup = "group"
let kselectedDate = "selectedDate"
let kuserCardId = "userCardId"
let kcustomerId = "customerId"
let kcardBrand = "cardBrand"
let klast4 = "last4"
let kisfreeconsult = "isfreeconsult"

let kuserSarchHistoryId = "userSarchHistoryId"

let kgoalId = "goalId"
let kgoalText = "goalText"
let kgoalName = "goalName"
let kuserAppointmentId = "userAppointmentId"
let kpainScale = "painScale"
let kfunctionScale = "functionScale"
let kcomplaintGetting = "complaintGetting"
let kappointmentBookId = "appointmentBookId"

//Appointment
let ktext = "text"
let kprice = "price"

//Transaction
let ktransactionId = "transactionId"
let kpayType = "payType"
let kamount = "amount"
let kuserTransactionDate = "userTransactionDate"
let kamountFormatted = "amountFormatted"
let kwalletAmountFormat = "walletAmountFormat"
let kwalletAmount = "walletAmount"
let kstripe_connect_satus = "stripe_connect_satus"
let kwalletAmountInFormat = "walletAmountInFormat"
let kwalletAmountOutFormat = "walletAmountOutFormat"

//VOIP
let kaccess_token = "access_token"
let kreceiverData = "receiverData"
let ksenderData = "senderData"
let kroom_name = "room_name"
let kcategory = "category"
let kmessageData = "messageData"
let kunread = "unread"
let kvoipToken = "voipToken"
let kgroupId = "groupId"

//Apple Signin
let kAppleSigninEmail : String = "AppleSigninEmail"
let kAppleSigninFirstName : String = "AppleSigninFirstName"
let kAppleSigninLastName : String = "AppleSigninLastName"
let kAppleSigninAppUserID : String = "AppleSigninAppUserID"
let kAppleSigninUserData : String = "AppleSigninUserData"

//Refer
let knextAvailablettt = "nextAvailablettt"
let kreferProviderData = "referProviderData"
let kfreeConsultUserData = "freeConsultUserData"
let kfreeConsultStatus = "freeConsultStatus"
let kfreeConsultDoctorData = "freeConsultDoctorData"

let kdesc = "desc"
let kmodel = "model"
let kmodel_id = "model_id"
let ksend_from = "send_from"
let ksend_to = "send_to"
let ksenderId = "senderId"
let ksenderRole = "senderRole"
let ktime_ago = "time_ago"

let khearAboutUsId = "hearAboutUsId"
let kfamilyVaccinated = "familyVaccinated"
let ksoonPlanningHireDate = "soonPlanningHireDate"
let khearAboutUs = "hearAboutUs"
let klicenceTypeId = "licenceTypeId"
let klicenceType = "licenceType"

let kuserCertificationsLicensesId = "userCertificationsLicensesId"
let klicenceName = "licenceName"
let klicenceNumber = "licenceNumber"
let kissueDate = "issueDate"
let kexpireDate = "expireDate"
let klicenceImageName = "licenceImageName"
let klicenceImage = "licenceImage"
let klicenceImageUrl = "licenceImageUrl"
let klicenceImageThumbUrl = "licenceImageThumbUrl"
let klicenceTypeName = "licenceTypeName"
let khaveCertificationsOrLicenses = "haveCertificationsOrLicenses"
let kcertificationsOrLicenses = "certificationsOrLicenses"
let khaveInsurance = "haveInsurance"
let kinsurance = "insurance"

let kjobCategoryId = "jobCategoryId"
let kimageThumbUrl = "imageThumbUrl"

let kuserWorkExperienceId = "userWorkExperienceId"
let kworkPlace = "workPlace"
let kstartDate = "startDate"
let kendDate = "endDate"
let kleavingReason = "leavingReason"

let kworkDisabilitiesWillingTypeId = "workDisabilitiesWillingTypeId"
let kworkSpecialityId = "workSpecialityId"
let kinsuranceTypeId = "insuranceTypeId"
let kworkMethodOfTransportationId = "workMethodOfTransportationId"

let kworkDisabilitiesWillingType = "workDisabilitiesWillingType"
let kworkMethodOfTransportation = "workMethodOfTransportation"
let kworkSpeciality = "workSpeciality"
let kinsuranceType = "insuranceType"
let kjobCategory = "jobCategory"
let kmaxDistanceTravel = "maxDistanceTravel"
let kexperienceOfYear = "experienceOfYear"
let kinspiredYouBecome = "inspiredYouBecome"
let kworkExperience = "workExperience"

let kuserInsuranceId = "userInsuranceId"
let kinsuranceName = "insuranceName"
let kinsuranceNumber = "insuranceNumber"
let kinsuranceImageName = "insuranceImageName"
let kinsuranceImageUrl = "insuranceImageUrl"
let kinsuranceImageThumbUrl = "insuranceImageThumbUrl"
let kinsuranceTypeName = "insuranceTypeName"

let kuserJobId = "userJobId"
let kformatedPrice = "formatedPrice"
let ktotalApplication = "totalApplication"
let kstartDateTime = "startDateTime"
let kCategoryName = "CategoryName"
let kcreatedDateFormat = "createdDateFormat"
let kuserJobMediaId = "userJobMediaId"
let kjobId = "jobId"
let kisVideo = "isVideo"
let kvideoImage = "videoImage"
let kmediaNameUrl = "mediaNameUrl"
let kmediaNameThumbUrl = "mediaNameThumbUrl"
let kvideoImageUrl = "videoImageUrl"
let kvideoImageThumbUrl = "videoImageThumbUrl"

let kuserJobQuestionId = "userJobQuestionId"
let kquestion = "question"

let kownTransportation = "ownTransportation"
let knonSmoker = "nonSmoker"
let kcurrentEmployment = "currentEmployment"
let kminExperience = "minExperience"
let kyearExperience = "yearExperience"
let kadditionalQuestions = "additionalQuestions"
let kdate = "date"
let kjobTiming = "jobTiming"
let kisJob = "isJob"
let kmedia = "media"
let kVideoThumbnail = "VideoThumbnail"

let kisHire = "isHire"
let kuserFullName = "userFullName"
let kprofileImageUrl = "profileImageUrl"
let kprofileImageThumbUrl = "profileImageThumbUrl"
let kdistance = "distance"
let kisFirst = "isFirst"
let kisBehavioral = "isBehavioral"
let kisVerbal = "isVerbal"
let kquestionId = "questionId"
let kquestionsAnswer = "questionsAnswer"
let kisJobApply = "isJobApply"

let kupcomingJobs = "upcomingJobs"
let knearestJobs = "nearestJobs"
let kcategories = "categories"
let ktimezone = "timezone"
let kjobStatus = "jobStatus"
let kuserJobApplyId = "userJobApplyId"
let kcaregiverId = "caregiverId"
let kattachmentRealName = "attachmentRealName"
let kcategoryNames = "categoryNames"
let kfullName = "fullName"
let ktotalJobCompleted = "totalJobCompleted"
let ksuggestedProvider = "suggestedProvider"


let kcaregiverBio = "caregiverBio"
let ktotalJobs = "totalJobs"
let ksuccessPercentage = "successPercentage"
let ktotalJobsHours = "totalJobsHours"
let kworkSpecialityName = "workSpecialityName"
let kworkMethodOfTransportationName = "workMethodOfTransportationName"
let kworkDisabilitiesWillingTypeName = "workDisabilitiesWillingTypeName"
let kworkDistancewillingTravel = "workDistancewillingTravel"
let ktotalYearWorkExperience = "totalYearWorkExperience"
let kworkExperienceData = "workExperienceData"
let kuserWorkJobCategoryId = "userWorkJobCategoryId"
let kcategoryData = "categoryData"

let kuserWorkDetailId = "userWorkDetailId"
let kworkDisabilitiesWillingTypeData = "workDisabilitiesWillingTypeData"
let kuserWorkJobDisabilitiesWillingTypeId = "userWorkJobDisabilitiesWillingTypeId"
let kinsuranceImage = "insuranceImage"

let kuserJobDetailId = "userJobDetailId"
let ktotalTiming = "totalTiming"
let ktotalMinutes = "totalMinutes"
let kTotalSeconds = "TotalSeconds"
let kjobRating = "jobRating"

let kfeed = "feed"
let kimageVideo = "imageVideo"
let kfeedId = "feedId"
let kformatedTime = "formatedTime"
let kisLiked = "isLiked"
let ktotalLikes = "totalLikes"
let ktotalComments = "totalComments"
let kvideoThumbImage = "videoThumbImage"
let kcomment = "comment"
let kformatedCreatedDate = "formatedCreatedDate"
let kcommentId = "commentId"
let kvideoThumbImgName = "videoThumbImgName"
let ktotalFeedLike = "totalFeedLike"
let kcreatedTime = "createdTime"
let ktotalFeedComment = "totalFeedComment"
let kuserFeedId = "userFeedId"
let kisLike = "isLike"
let kfeedCommentId = "feedCommentId"
let kuserFeedLikeId = "userFeedLikeId"
let kjobFeedback = "jobFeedback"
//let koldPassword = "oldPassword"
/*let k = ""
let k = ""
let k = ""
let k = ""
let k = ""*/

//Bank
let kaccount_holder_name = "account_holder_name"
let kaccount_holder_type = "account_holder_type"
let krouting_number = "routing_number"
let kaccount_number = "account_number"
let kcurrency = "currency"
let kwithdrawableAmount = "withdrawableAmount"
//Connected Acount
let kisPayout = "isPayout"
let kisPayment = "isPayment"
let kconnectAccount = "connectAccount"
let kisStripeConnect = "isStripeConnect"
let kisBankDetail = "isBankDetail"

//Stripe
let kaccId = "accId"
let kurl = "url"
let kstripe_connect_status = "stripe_connect_status"
let ktotalIncome = "totalIncome"
let ktotalwithdrawIncome = "totalwithdrawIncome"
let knoofwithdraw = "noofwithdraw"

let kuserTransactionId = "userTransactionId"
let ktranType = "tranType"
let kuserTransactionTime = "userTransactionTime"
let kcaregiverName = "caregiverName"
let kjobName = "jobName"

let kuserReviewId = "userReviewId"
let kuserIdFrom = "userIdFrom"
let kuserIdTo = "userIdTo"
let kreviewDate = "reviewDate"
let kreviewData = "reviewData"
let ktotalReview = "totalReview"
let knotificationCount = "notificationCount"
let kchatCount = "chatCount"

let kthumbSenderImage = "thumbSenderImage"
let ktotalWorkTime = "totalWorkTime"
let kinboxMsgText = "inboxMsgText"
let kinboxMsgMail = "inboxMsgMail"
let kjobMsgText = "jobMsgText"
let kjobMsgMail = "jobMsgMail"
let kcaregiverUpdateText = "caregiverUpdateText"
let kcaregiverUpdateMail = "caregiverUpdateMail"

let kallergiesName = "allergiesName"
let kspecialitieId = "specialitieId"
let kisFamilyVaccinated = "isFamilyVaccinated"
let kisJobType = "isJobType"
let kstartMiles = "startMiles"
let kendMiles = "endMiles"
let kdates = "dates"
let krepeatType = "repeatType"

let kuserAvailabilitySettingNewId = "userAvailabilitySettingNewId"
let kuserPhone = "userPhone"
let kuploadedMedia = "uploadedMedia"
let kuserJobSubstituteRequestId = "userJobSubstituteRequestId"
let ksubstituteRequestId = "substituteRequestId"

let kstartTimeStamp = "startTimeStamp"
let kendTimeStamp = "endTimeStamp"
let kcaregiverStartTimeStamp = "caregiverStartTimeStamp"
let kcaregiverEndTimeStamp = "caregiverEndTimeStamp"
let kcaregiverStartDateTime = "caregiverStartDateTime"
let kcaregiverEndDateTime = "caregiverEndDateTime"
let kslot = "slot"
let kduration = "duration"
let kendDateTime = "endDateTime"
//let kuserJobSubstituteRequestId = "userJobSubstituteRequestId"
//let ksubstituteRequestId = "substituteRequestId"
let knewCaregiverId = "newCaregiverId"
let kavailabilityId = "availabilityId"
let krequestStartTime = "requestStartTime"
let krequestEndTime = "requestEndTime"
let kperviousHours = "perviousHours"
let kupdatedHours = "updatedHours"
let kstartJobStatus = "startJobStatus"
let kongoingJobPendingTiming = "ongoingJobPendingTiming"
let kongoingJobPendingMinutes = "ongoingJobPendingMinutes"
let kongoingJobPendingSeconds = "ongoingJobPendingSeconds"
let kuserJobAwardId = "userJobAwardId"
