package com.app.xtrahelpcaregiver.Response

data class CaregiverRelatedJobDetailResponse(
    var `data`: Data,
    var message: String,
    var status: String
) {
    data class Data(
        var CategoryName: String,
        var categoryId: String,
        var createdDate: String,
        var createdDateFormat: String,
        var currentEmployment: String,
        var description: String,
        var distance: String,
        var formatedPrice: String,
        var isHire: String,
        var isJob: String,
        var jobFeedback: String,
        var jobRating: String,
        var jobStatus: String,
        var latitude: String,
        var location: String,
        var longitude: String,
        var media: ArrayList<Media>,
        var uploadedMedia: ArrayList<Media>,
        var minExperience: String,
        var name: String,
        var startJobStatus: String,
        var nonSmoker: String,
        var ownTransportation: String,
        var price: String,
        var profileImageThumbUrl: String,
        var profileImageUrl: String,
        var questions: ArrayList<Question>,
        var startDateTime: String,
        var status: String,
        var userFullName: String,
        var userId: String,
        var userJobApplyId: String,
        var userJobId: String,
        var userJobDetailId: String,
        var userJobIsHire: String,
        var yearExperience: String,
        var verificationCode: String,
        var starTimestamp: String,
        var endTimestamp: String,
        var caregiverId: String,
        var ongoingJobPendingTiming: String,
        var ongoingJobPendingMinutes: String,
        var ongoingJobPendingSeconds: String,
    )
}