package com.app.xtrahelpcaregiver.Response

data class Job(
    var categoryId: String,
    var createdDate: String,
    var currentEmployment: String,
    var description: String,
    var formatedPrice: String,
    var isHire: String,
    var isJob: String,
    var jobStatus: String,
    var latitude: String,
    var location: String,
    var longitude: String,
    var minExperience: String,
    var name: String,
    var nonSmoker: String,
    var ownTransportation: String,
    var price: String,
    var userJobDetailId: String,
    var profileImageThumbUrl: String,
    var profileImageUrl: String,
    var startDateTime: String,
    var status: String,
    var userFullName: String,
    var userId: String,
    var userPhone: String,
    var userJobApplyId: String,
    var userJobId: String,
    var userJobIsHire: String,
    var yearExperience: String
)